name: Cleaner Report
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 7 * * 6'
  workflow_dispatch:
jobs:
  report_to_me:
    runs-on: windows-2022
    name: "Report to Me!"
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Report to Me
        run: dotnet run --project CleanerReport
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          EMAIL_TARGET: ${{ secrets.EMAIL_TARGET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}



