name: Cleaner Report
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 7 * * 6'
  workflow_dispatch:
jobs:
  report_to_me:
    runs-on: ubuntu-22.04
    name: "Report to Me!"
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Report to Me
        run: dotnet run --project CleanerReport
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          EMAIL_TARGET: ${{ secrets.EMAIL_TARGET }}